---
title: "Prep_Code Page"
author: "Greg"
date: "8/6/2020"
output: html_document
---

```{r}
library(shiny)
library(tidyverse)
library(shinydashboard)
library(RColorBrewer)
library(tidyr)
famer = read.csv('famer.csv')

fun = function(x){
  str_sub(x, 3,-3)
}

famer$track_artists = sapply(famer$track_artists, fun )
famer = separate(famer, track_artists, sep = "', '", c('first_artist','second_artist','third_artist','fourth_artist', 
          'fifth_artist', "sixth', 'seventh','eighth_artist(s)'"), extra = 'merge')

famer$number_of_artists = apply(famer, 1, ( function(x) sum(is.na(x))*-1 +6) )

famer$number_of_artists[2883] = 8

```
```{r}
x = unlist(famer[4:8])
x1 = x[!is.na(x)]
x2 = as.data.frame(x1)
x3 = x2 %>% 
  rbind('Yo Gotti', 'Quavo', 'Desiigner', 'Paul Shaffer', 'Metallica')
```
```{r}
total_tracks = x3 %>% 
  count(x1, sort = TRUE, name = "Total_Artist_Tracks")
```
```{r}
total_tracks %>% 
  slice_max(Total_Artist_Tracks, n = 3)
```
```{r}
#make it so that slider starts with just #1...then slide to more
total_tracks$Artist = total_tracks$x1
total_tracks %>% 
  slice_max(Total_Artist_Tracks, n = 3) %>% 
  ggplot() +
  geom_col(mapping = aes(x = Artist, y = Total_Artist_Tracks, fill = Artist)) + 
  coord_flip() +
  theme(legend.position = "none")
```
```
```{r}
famer$playlist_name
class(famer$popularity)
```

```{r}
####this does not work yet #####
famer %>% 
  group_by(playlist_name, popularity) %>% 
  summarize(playlist_average = mean(popularity)) %>%
  ggplot(mapping = aes(x = playlist_name, y = playlist_average )) + 
  geom_box()
```

